# Generated by Django 3.1.3 on 2020-12-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronometer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='onfocus',
            field=models.CharField(default='others', max_length=20),
        ),
    ]
