# Generated by Django 3.1.3 on 2020-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronometer', '0003_timer_totaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='totalTime',
            field=models.FloatField(null=True),
        ),
    ]
